name: Dart compile from bin
run-name: Compile binary from bin
on:
  push:
    branches: [main 'releases/**']
jobs:
  compile:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1
